spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 8111054yt
  jpa:
    hibernate:
      ddl-auto: update